### ISSUE TITLE
How do you plainToClass to existing variables

### ISSUE THREAD

**Issue by face08** [pleerock/class-transformer#103]
I want to assign a value to a variable that already exists
Just like the following

`
let photos = new Photo();
plainToClass(photos,Photo, photosJson);
`

**Comment by Petr0vi4** [comment]
You can use `plainToClassFromExist` method, for example 
```
let photos = new Photo();
plainToClassFromExist(photos, photosJson);
```

**Comment by face08** [comment]
@Petr0vi4 
Thanks a lot.
