### ISSUE TITLE
[question] Missing licence information

### ISSUE THREAD

**Issue by szkumorowski** [pleerock/class-transformer#111]
Hi, Actually I don't see any information about licence - could you include it in the repository or write information about it ?

**Comment by NoNameProvided** [comment]
Hi @szkumorowsi, the license is most likely MIT as in the other projects of @pleerock.

**Comment by pleerock** [comment]
yes its MIT, you can find it in package.json file.

**Comment by gempain** [comment]
Shouldn't we have a LICENSE.md file at the root of the project ? Usually, a copy of the license is supposed to be distributed with the sources.

**Comment by NoNameProvided** [comment]
It's not needed if it mentioned in the package.json than it's enough, but feel free to add a PR.
