### ISSUE TITLE
Transform Dates into moment

### ISSUE THREAD

**Issue by prbaron** [pleerock/class-transformer#12]
Hi,

Is it possible to use the @Type decorator to transform a date string into a moment object when calling plainToClass ?

**Comment by pleerock** [comment]
Don't think that right now its possible, but I'll think if there ways to implement this

**Comment by pleerock** [comment]
Now its possible, checkout latest version of class-transformer. See more info [here](https://github.com/pleerock/class-transformer#additional-data-transformation).
