### ISSUE TITLE
Does not seem to work with generic object

### ISSUE THREAD

**Issue by johnchanck** [pleerock/class-transformer#14]
I have a class with an array of generic objects.  I tried specifying the @Type decorator but it doesn't seem to be working.  Am I doing something wrong or are generics not supported?  Thank you.

class JsonObject {
    @Type(() => KeyValuePair\<Date, number>)
    public Series: KeyValuePair\<Date, number>[] = [];
}

**Comment by pleerock** [comment]
Can you show `KeyValuePair` source, and also show that you are sending to class transformer and what you are expecting

**Comment by johnchanck** [comment]
Hello, thanks for looking into this.

Here are my actual class and json string:

```typescript
import {Type, plainToClass} from "class-transformer";

class KeyValuePair<TKey, TValue>
{
    //@Type(() => TKey) // how to type this?
    public Key: TKey;
    //@Type(() => TValue) // how to type this?
    public Value: TValue;
}

class Data
{
    public Name: string = null;
    public Description: string = null;
    //@Type(() => KeyValuePair) // how to type this?
    public Temperature: KeyValuePair<string, KeyValuePair<Date, number>[]>[] = [];
    //@Type(() => KeyValuePair) // how to type this?
    public Humidity: KeyValuePair<string, KeyValuePair<Date, number>[]>[] = [];
}

const deserialized = plainToClass(Data, {
    "Name": "Project ABC",
    "Description": "My analysis",
    "Temperature": [
        {
            "Key": "Kitchen",
            "Value": [
                {
                    "Key": "2016-05-31T00:00:00",
                    "Value": 1
                },
                {
                    "Key": "2016-06-30T00:00:00",
                    "Value": 2
                }
            ]
        },
        {
            "Key": "Bedroom",
            "Value": [
                {
                    "Key": "2016-05-31T00:00:00",
                    "Value": 3
                },
                {
                    "Key": "2016-06-30T00:00:00",
                    "Value": 4
                }
            ]
        }
    ],
    "Humidity": [
        {
            "Key": "Kitchen",
            "Value": [
                {
                    "Key": "2016-05-31T00:00:00",
                    "Value": 5
                },
                {
                    "Key": "2016-06-30T00:00:00",
                    "Value": 6
                }
            ]
        },
        {
            "Key": "Bedroom",
            "Value": [
                {
                    "Key": "2016-05-31T00:00:00",
                    "Value": 7
                },
                {
                    "Key": "2016-06-30T00:00:00",
                    "Value": 8
                }
            ]
        }
    ]
});
```

**Comment by pleerock** [comment]
Unfortunately using generics this way will not work. It would be great to have it, but infortunatelly its simply not possible until Typescript introduce some good reflection tools and capabilities. In my projects I forced to use monkey patches like this:

```typescript
export class Collection<T> {

    count: number;

    @Type((newCollection: Collection<T>) => newCollection.type)
    list: T[];
    
    @Exclude()
    private type: Function;

    constructor(list?: T[], count?: number, type?: Function) {
        this.list = list;
        this.count = count;
        this.type = type;
    }
    
}
```

In this code I have to implicitly specify a type to class, save it and use to show to class-transformer what type is being used by this generic.

**Comment by pleerock** [comment]
make sure you have a latest version and take a look on example [here](https://github.com/pleerock/class-transformer/tree/master/sample/sample4-generics)

**Comment by johnchanck** [comment]
I've been trying to get your sample to work but have not been successful.  I think my problem is that I am unable to pass the constructor function of the generic class to the plainToClass function.  I'd appreciate it if you could take a look at it.  Here is the code I'm working with; the last line gives an error in TypeScript.  

```typescript
import {Type, Exclude, plainToClass} from "class-transformer";

class Foo
{
    Name: string;
}

class Specific
{
    @Type(() => Foo)
    Values: Foo[] = null;
}

class Generic<T>
{
    @Type(options => (options.newObject as Generic<T>).type)
    Values: T[] = null;
    @Exclude()
    private type: Function;
    constructor(type: Function)
    {
        this.type = type;
    }
}

let obj =
    {
        "Values": [
            { "Name": "abc" }
        ]
    };

console.log(plainToClass(Specific, obj)); // <-- this works
console.log(plainToClass(new Generic<Foo>(Foo), obj)); // <-- this does not work
```

**Comment by pleerock** [comment]
yeah plainToClass will not work here. you need to use plainToClassFromExist instead:

```plainToClassFromExist(new Generic<Foo>(Foo), obj)```

**Comment by johnchanck** [comment]
Thank you!  It works now.  I've been struggling with this for the past few days!

**Comment by pleerock** [comment]
np

**Comment by johnchanck** [comment]
I managed to create a KeyValuePair generic class as follows:
```typescript
class KeyValuePair<TKey, TValue>
{
    @Type(o => (o.newObject as KeyValuePair<TKey, TValue>).TKey)
    public Key: TKey = null;
    @Type(o => (o.newObject as KeyValuePair<TKey, TValue>).TValue)
    public Value: TValue = null;
    @Exclude() public TKey: Function = null;
    @Exclude() public TValue: Function = null;
    public constructor(TKey: Function, TValue: Function)
    {
        this.TKey = TKey;
        this.TValue = TValue;
    }
}
```
plainToClassFromExist works with primitive types and simple classes.  However, I am unable to make it work with nested generic types like so:

```typescript
KeyValuePair<String, KeyValuePair<String, Number>>
```

Do you know of any workarounds?  My main problem is that I do not know how to get the constructor function of the generic class with types specified: KeyValuePair\<String,Number\> to pass to the outer KeyValuePair's constructor.  Pardon me, I am new to TypeScript.

**Comment by pleerock** [comment]
everything you need to know you already know - you know that there is a plainToClassFromExist, and that `@Type` can give you a transformed object in the function that you can manipulate. Now make experiments and try to figure out how to resolve additional problems. But generally its hard to use this component with generics, so anything you would do may look like monkey patch

**Comment by johnchanck** [comment]
Thanks, I really appreciate the help!
