### ISSUE TITLE
Exposing properties with different names

### ISSUE THREAD

**Issue by andrui** [pleerock/class-transformer#17]
There is a mistake in [documentation](https://github.com/pleerock/class-transformer#exposing-properties-with-different-names) (I guess):

```typescript
    @Expose("uid")
    id: number;
```

But Expose has only one argument - ExposeOptions
In such a case should be

```typescript
    @Expose({name: "uid"})
    id: number;
```

**Comment by pleerock** [comment]
yes, you are right, its a mistake in documentation. Use `@Expose({name: "uid"})` this syntax

**Comment by pleerock** [comment]
docks are fixed
