### ISSUE TITLE
DevTools failed to parse SourceMap

### ISSUE THREAD

**Issue by dylanparry** [pleerock/class-transformer#18]
Since adding Class Transformer to my project, I'm getting the error:

```
DevTools failed to parse SourceMap: http://localhost:62691/scripts/TransformMetadata.js.map
```

I’m building my project Webpack and the TS-Loader module, if that's of any relevance. My `tsconfig.json` also has `SourceMap` set to `false`, so there shouldn't be any getting generated anyway!

Is this in issue with Class Transformer or with the Reflect Metadata package? Any help is greatly appreciated.

Thanks,

Dylan

**Comment by dylanparry** [comment]
I've managed to get rid of the error by adding `devtool: 'source-map'` to my Webpack configuration. Not a proper fix as I now have source maps when I didn't want them, but it works so it'll do.

**Comment by pleerock** [comment]
sorry I haven't worked with webpack and thus can't provide any info about this issue. But if you'll find a reason why you have this, or find any error in the library, please let know
