### ISSUE TITLE
truncate object .

### ISSUE THREAD

**Issue by yantrab** [pleerock/class-transformer#42]
hi, how can i truncate object that i get from the client.
suppose i have class:

```
class user{
id:string;
appId:string;
}
```

and i get userViewModel from client that contains appName;

what that i did, i set all property to null, and do:
```
obj = new type();
                _.each(_.keys(obj), key =>{
                    obj[key] = data[key];
                    if (obj[key] === null) obj[key] = undefined; 
                })

```
there is a better way to do it with your module?

tanks.

**Comment by Petr0vi4** [comment]
If you run this sample
```typescript
@Exclude()
class User {
  @Expose() id: string;
  @Expose() appId: string;
}

let obj = {
  id: 'testId',
  appId: 'testAppId',
  appName: 'testAppName',
};

let user = plainToClass(User, obj);

console.log(user);
```
output will be
```
User
  appId: "testAppId"
  id: "testId"
  __proto__: Object
```
Is this what you need?

**Comment by yantrab** [comment]
yes , it is grate. tanks.

2017-01-23 12:37 GMT+02:00 Петровский Александр <notifications@github.com>:
