### ISSUE TITLE
Different class by value

### ISSUE THREAD

**Issue by pschuster** [pleerock/class-transformer#50]
Hi,

I have a tree structure in json. Imagine a folder-file system, with various different file types. I want the files array to be different classes based on the extension of the entry.

I played around with the @Transform decorator but didn't have any success. Is this supported?

Thanks for your help.
Phillip

**Comment by Petr0vi4** [comment]
Did you tried somthing like [this ](https://plnkr.co/edit/p7TNGQsEyQ62zlqKl6Dy)?

**Comment by pschuster** [comment]
Thanks so much for providing this example. I think it makes sense to add that to the Wiki. It works fine, but I don't think I would have ever come up with that syntax ;-).

Thanks a lot!
Phillip
