### ISSUE TITLE
Ignore extra properties when creating instance from plain object

### ISSUE THREAD

**Issue by slavafomin** [pleerock/class-transformer#55]
Hello!

Please consider a use case where we are converting plain object to class object using `plainToClass()` and plain object has more properties than class supports, i.e. it contains extra ones. In current implementation, those properties are added to the newly created instance. However, I would like to avoid that.

Is there a way to disable adding of extra properties? Globally switch is preferred.

The only workaround I've found is to add `@Exclude()` to the entire class and then to `@Expose` each property manually. With this approach extra properties are ignored, but it could be tiresome to configure and readability is also suffer.

Thanks!

**Comment by slavafomin** [comment]
I've added a PR to demonstrate the idea.

**Comment by pleerock** [comment]
Its impossible to get know what properties class have without putting decorator on each property (this is how reflection-metadata works, and yeah, its very limited). So if you won't put decorator on `firstName` I will never know that such property exist in `User`.

**Comment by slavafomin** [comment]
Yes, that makes sense. I always forget about these limitations.
