### ISSUE TITLE
Angular 2/4 issues

### ISSUE THREAD

**Issue by gempain** [pleerock/class-transformer#66]
Amazing library, I have to say. It must become something big in the next few months/years.

I am working with the latest `angular-cli` and Angular 4, but having a few issues.

1. `classToPlain` not working properly. `@Exclude` are ignored, though using the same model in NodeJS works fine.
2. `classToPlain` throws
```
RangeError: Maximum call stack size exceeded.
```
see the following stack trace (I couldn't copy as text since Safari is crashing...)
<img width="617" alt="screen shot 2017-06-27 at 21 43 21" src="https://user-images.githubusercontent.com/13135149/27606872-29e119ba-5b82-11e7-85a5-0363f6b55872.png">

**Comment by pleerock** [comment]
You probably have a recursion on your object. Try to do that with simple objects. I use class-transformer on the frontend with angular 4 as well and don't have such issues.

**Comment by gempain** [comment]
I am pretty sure that my property does not have recursions in it... The first issue is weird though. Could be related to not importing correctly `reflect-metadata` and/or `es6-shim` ? I have placed those imports in `polyfills.ts`, though I am pretty sure they are not needed at all for Angular 4 already has
```
/** Evergreen browsers require these. **/
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';
```

**Comment by gempain** [comment]
Found a solution: I was importing my model from my backend project, which has its own `node_module` directory. Somehow, there was an import conflict somewhere. I copied and pasted the model into my front-end project, and now everything works fine. The only drawback I see to this is that every time I make a change to my backend model, I have to make that change to my front-end model as well.

**Comment by jotatoledo** [comment]
You could generate an interface in your backend that you then import into your frontend, that way you could be sure that the models match, withouth binding logic into the imported file

**Comment by gempain** [comment]
Good idea, plus I'm starting to think that front-end code should be separate from backend code. I may want some fields to exist in the backend while the front end is not aware of their existence, so the model will be similar but not an exact clone. I like the interface idea for defining the contract between client and server :)
