### ISSUE TITLE
Question: Using an Enum property

### ISSUE THREAD

**Issue by oferRounds** [pleerock/class-transformer#85]
Hi,

Small question please:
In the JSON data which I receive from the server, I have key which can be 1 of 5 different string types. I’d like to transform it on my class to use an Enum which represents these 5 values.

Is such thing possible? Wasn’t sure how to achieve that.

Would love for some help :)

Thanks for this awesome library!

**Comment by NoNameProvided** [comment]
It works with numerical types using the `@IsEnum` decorator. For string enums there is no support yet.

**Comment by oferRounds** [comment]
Got you, could you please give an example of the usage of `@isEnum`?

**Comment by NoNameProvided** [comment]
```ts
import { IsNotEmpty, IsEnum } from 'class-validator';

export enum Difficulty {
  Easy = 1,
  Medium = 2,
  Hard = 3,
}

export class MyClass {

  @IsNotEmpty()
  @IsEnum(Difficulty)
  public difficulty: Difficulty;

}
```

**Comment by oferRounds** [comment]
Cool! Thanks!
Maybe we should add it also to the documentation.

**Comment by gempain** [comment]
@NoNameProvided String enums are supported by class-validator. I made a PR that was merged a few months ago.

**Comment by NenadJovicic** [comment]
@gempain wondering is it still working
because currently have a problem with this
sending wrong string as some enum, and it didn't throw any error

**Comment by gempain** [comment]
@NenadJovicic yes I was having issues with enums too.

**Comment by NenadJovicic** [comment]
looks like it is not working only in nested object @gempain 
so, I got a validator with some enum check
```ts
export class PushSubscriptionDtoValidator extends PushSubscriptionDto {
    @IsNotEmpty({ message: ErrorType.PushSubscriptionRequired })
    @IsString({ message: ErrorType.PushSubscriptionRequired })
    pushToken: string;
    @IsNotEmpty({ message: ErrorType.PushDeviceTypeRequired })
    @IsEnum(DeviceType, { message: ErrorType.InvalidDeviceType })
    deviceType: DeviceType;

    constructor(subscription?: PushSubscriptionDtoValidator) {
        super(subscription);
    }
}
```
and then, got another validator that use this validator as a type of some property

```ts
export class LogoutDtoValidator implements LogoutDto {
    @IsOptional()
    @IsArray({ message: ErrorType.BadRequest })
    pushSubscriptions?: Array<PushSubscriptionDtoValidator> = [];
}
```

When I run some test that use as a body `PushSubscriptionDtoValidator`, it will throw a proper error for enum
But, when I use `LogoutDtoValidator` as a body, it won't validate this enum
But, interesting thing is, it will validate part about `@IsNotEmpty()` for both fields in `PushSubscriptionDtoValidator` when using LogoutDtoValidator

**Comment by gempain** [comment]
@NenadJovicic you have forgotten to use `@ValidateNested()` on your array, that's why `class-validator` is not recursively validating your array. I should have noticed it earlier, but here's a proof:

```ts
import {IsArray, IsEnum, IsNotEmpty, IsOptional, validate, ValidateNested} from 'class-validator';

export enum Enum {
    a = 'a',
}

export class Child {
    @IsNotEmpty()
    @IsEnum(Enum)
    enum: Enum;
}

export class Parent {
    @IsOptional()
    @IsEnum(Enum)
    enum?: Enum;
    @IsOptional()
    @IsArray()
    @ValidateNested()
    array?: Child[] = [];
}

describe('class validator enum', () => {
    describe('root object validation', () => {
        it('should validate enum on root object', async () => {
            const dto = new Parent();
            dto.enum = Enum.a;

            const validationErrors = await validate(dto);

            expect(validationErrors.length).toEqual(0);
        });

        it('should validate enum on root object', async () => {
            const dto = new Parent();
            dto.enum = 'val' as any;

            const validationErrors = await validate(dto);

            expect(validationErrors.length).toEqual(1);
        });
    });
    describe('nested validation', () => {
        it('should be valid when nested enum is valid', async () => {
            const dto = new Parent();
            const child = new Child();
            child.enum = Enum.a;
            dto.array.push(child);

            const validationErrors = await validate(dto);

            expect(validationErrors.length).toEqual(0);
        });
        it('should be invalid when nested enum is invalid', async () => {
            const dto = new Parent();
            const child = new Child();
            child.enum = 'val' as any;
            dto.array.push(child);

            const validationErrors = await validate(dto);

            expect(validationErrors.length).toEqual(1);
        });
    });
});
```

Which works fine on my side:
<img width="310" alt="Screenshot 2020-04-04 at 11 53 31" src="https://user-images.githubusercontent.com/13135149/78424024-ed6a5080-766a-11ea-924b-7592e3333661.png">

Remove the `@ValidateNested()` and you'll see the last test fails.
