### ISSUE TITLE
Someone should start closing issues

### ISSUE THREAD

**Issue by svallory** [pleerock/class-transformer#98]
I'm evaluating this package for use in a project and, right now, the number of open issues give the wrong impression. Reading through the issues I've found at least a few issues that can be closed. It also makes it harder for people wanting to help to find things to contribute.

**Comment by pleerock** [comment]
Thank you for pointing this problem. Would be great if someone can take an initiative and help me to maintain this package. Currently Im really busy with other open source projects which are much more complex then this one and take too much time. I was planning to return to this package and fix/close all issues once I get free from other packages

**Comment by gempain** [comment]
@pleerock I can help you :) I actually started writing you an email a while back, but ended up deciding not to. My only worry is I don't want to take responsibility for accepting PRs.

**Comment by svallory** [comment]
I'm not going to promise long term help, but I'll use it to serialize/deserialize classes cross packages in a framework I'm finishing up plus at least half a dozen projects in production. Make me a contributor and I'll at least crush bugs on my way and close a few issues

**Comment by svallory** [comment]
Btw, @pleerock, what do you think about splitting the serialize part to another project (serializer.ts?) and keeping class transformation (to plain, from plain and to class) in this one? I think separating and simplifying the API would help new users.

There are a couple things I think could be removed too, like `deserializeArray` and `@TransformClassTo*` method decorators (we can just call `classTo*` on the value to be returned, right?)

Let me know how you feel about that.

**Comment by gempain** [comment]
@pleerock I've sent you an email a few days back now. Have you received it ? (gmail address)

**Comment by NoNameProvided** [comment]
@svallory 
> Make me a contributor and I'll at least crush bugs on my way and close a few issues

You don't have to be a contributor to start fixing bugs, you can start sending PR-s now as well, if you have time to fix them. 

@gempain

@pleerock is very busy right know with TypeORM, pinging here every few day if he read the email or not won't get you a faster answer. 

Ca 2 weeks from now he will move most of the repos (at least class-validator, class-tranformer and routing-controllers) under the typestack org so I will be able to close the issue and merge PR-s. Also that's will be the right time to ask your questions as he will be looking actively on the issues in those repos.

**Comment by gempain** [comment]
@NoNameProvided Not trying to get a faster answer. @pleerock asked for help from the community (read up this thread):

> Would be great if someone can take an initiative and help me to maintain this package.

I was just offering.

**Comment by svallory** [comment]
@NoNameProvided OK, will do. On a side note, I just reached out to @TypeForce to join forces with @cashfarm because both orgs are working on Typescript tools. Maybe we should form a coalition :)

**Comment by pleerock** [comment]
@gempain I got your email, thanks. As @NoNameProvided told you need to start answering in all opened and help people with their questions. Once they get answers they can close issues by themself. If there are bugs or issues needs to be fixed, they must be discussed first, then implemented until its something minor. I'll start actively closing and responding in this repository in 2-3 weeks, Im quite busy at the moment.
